version: "3"
services:
  mcserver:
    build:
      context: .
    command: # /google-cloud-sdk/bin/gsutil -m rsync -r -d gs://project-secret-minecraft-backup-weekly/20200928-020001-world /world
      - sh
      - -c
      - |
        screen -dmS mc java -Xmx1024M -Xms1024M -jar minecraft_server.jar nogui
        sleep infinity
    container_name: mcserver
    ports:
      - 25565:25565
    volumes:
      - savefiles:/mc/world
      - ${HOME}/.config:/root/.config:ro
volumes:
  savefiles:
