version: "3"
services:
  mcserver:
    build:
      dockerfile: Dockerfile-mcserver
    command: java -Xmx1024M -Xms1024M -jar minecraft_server.jar nogui
    container_name: mcserver
    ports:
      - 25565:25565
    volumes:
      - savefiles:/mc/world
volumes:
  savefiles:
