services:
  mcserver:
    build:
      context: .
    profiles:
      - server
      - restore
    command:
      - sh
      - -c
      - |
        screen -dmS mc java -Xmx1024M -Xms1024M -jar minecraft_server.jar nogui
        sleep infinity
    container_name: mcserver
    ports:
      - 25565:25565
    volumes:
      - savefiles:/mc/world
      - ${HOME}/.config/gcloud:/root/.config/gcloud
  restore_saves:
    image: google/cloud-sdk:alpine
    build:
      context: .
    profiles:
      - restore
    command:
      - sh
      - -c
      - |
        rm -rf /mc/world/* \
        && gcloud storage cp "$(gcloud storage ls -l gs://project-secret-minecraft-backup gs://project-secret-minecraft-backup-weekly | sort -k 2 | tail -3 | head -1 | grep -Po '[^ ]+$')" - | tar -xzvf - -C /mc/world
      # - |
      #   gcloud storage rsync -r --delete-unmatched-destination-objects \
      #   gs://project-secret-minecraft-backup-weekly/20200928-020001-world /mc/world
    volumes:
      - savefiles:/mc/world
      - ${HOME}/.config/gcloud:/root/.config/gcloud
volumes:
  savefiles:
